<img style="float: left;" src="https://github.com/David-Kyrat/13X004-image-processing/blob/master/tp01/images/unige_csd.png?raw=1" alt="drawing" width="200"/>

# <center>Imagerie Numérique 2023 Automne</center>

<center>September 28, 2023</center>

# <center><ins>TP Class N°1 - Basics</ins></center>

#### *Instructions :*  

* This TP should be completed and uploaded on Moodle before **Thursday 12 October 2023, 23h59**.
* The name of the file you upload should be **TP1_name_surname.ipynb**.
* If you need to include attached files to you TP (images, python files, ...), please archive them together in a **ZIP** folder named **TP1_name_surname.zip**.

### Exercise 1 : Color Channels
*(1 point)*

Read the image *colors.jpg*.  

(a) Display the original image using *matplotlib*.

Listing images present in images folder for easier access:

In [ ]:
import os
os.listdir("images")

['logo_cui.jpg',
 'colors.jpg',
 'lena.png',
 'color_grad.png',
 'grad.png',
 'black_and_white.png',
 'unige_csd.png']

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import shape, uint8 as u8, uint32 as u32, float64 as f64
from copy import deepcopy

# Matplotlib use PIL to render images
from PIL import Image

colors_jpg = Image.open("images/colors.jpg").convert('L')

#! Watch out for overflow later on:
colors_jpg_nparr = np.asarray(colors_jpg, dtype=u8)
shape = *colors_jpg_nparr.shape, 3
tmp = np.zeros(shape)
print(tmp.shape)
colors_jpg_nparr = np.asarray(colors_jpg, dtype=u8, like=tmp)

(1600, 2560, 3)
[[ 37  37  35 ...  45  45  45]
 [ 36  35  34 ...  45  44  44]
 [ 34  34  34 ...  44  44  44]
 ...
 [ 10  10  10 ... 106 106 106]
 [ 10  10  10 ... 107 107 107]
 [ 10  10  10 ... 107 107 107]]


In [ ]:
# Plotting functions
import matplotlib.pyplot as plt
import numpy as np
from typing import List

def plotVS(plot_x, plot_f1, plot_f2, title: str = None, xlabel: str = None, ylabel: str = None, f1Label: str = None, f2Label: str = None):
    """Plots two functions against each other.
    - plot_x: the x-axis values
    - plot_f1: the y-values of the first function
    - plot_f2: the y-values of the second function
    - title: the title of the plot
    - xlabel: the label of the x-axis
    - ylabel: the label of the y-axis
    - f1Label: the label of the first function
    - f2Label: the label of the second function
    """

    # plt.subplot(3, 1, subp_idx)
    # plt.tight_layout()
    plt.grid()
    if title: plt.title(title)
    m1, m2, gap = min(plot_f2), max(plot_f1), 0.2
    plt.ylim(m1, m2 - gap * m2)
    if xlabel: plt.xlabel(xlabel)
    if ylabel: plt.ylabel(ylabel)
    plt.xticks(plot_x)
    if f1Label:  plt.plot(plot_x, plot_f1, '-k', label=f1Label, linewidth=1)
    else: plt.plot(plot_x, plot_f1, '-k', linewidth=1)

    if f2Label: plt.plot(plot_x, plot_f2, '-r', label=f2Label, linewidth=1)
    else: plt.plot(plot_x, plot_f2, '-r', linewidth=1)

    #plt.legend(prop={'size': 5})
    #plt.legend(fontsize=7)
    plt.legend()
    plt.show()

def plot_solo(plot_x, plot_f, title: str = None, xlabel: str = None, ylabel: str = None, fLabel: str = None):
    """Plots a single function
    - plot_x: the x-axis values
    - plot_f: the y-values of the function
    - title: the title of the plot
    - xlabel: the label of the x-axis
    - ylabel: the label of the y-axis
    - fLabel: the label of the function
    """
    #plt.tight_layout(pad=5)
    fig = plt.figure()
    if title: plt.title(title)
    plt.grid()
    if xlabel: plt.xlabel(xlabel)
    if ylabel: plt.ylabel(ylabel)
    M, gap = max(plot_f), 0.25

    plt.xticks(plot_x)
    #plt.ylim(0, M + gap*M)
    plt.yticks(np.linspace(0, M, 27))
    if fLabel:
        plt.plot(plot_x, plot_f, '-b', label=fLabel, linewidth=1)
    else:
        plt.plot(plot_x, plot_f, '-b')
    #  plt.legend(prop={'size': 5})
    #  plt.legend(fontsize=7)
    fig.set_figheight(7)
    plt.legend()
    print("\nshowing plot\n")
    plt.show()
    #fig.show()
    #fig.tight_layout()


(b) On a 1x3 subplot, display the three color components separately using correctly chosen colormaps.  
(That is, 'Reds_r' for red, 'Greens_r' for green and 'Blues_r' for blue)

In [ ]:
# for each col take 1st col of that col => red, 2nd col of that col => green, 3rd col of that col => blue
#reds = np.array([colors_jpg[i][:, 0] for i in range(len(colors_jpg))])
#greens = np.array([colors_jpg[i][:, 1] for i in range(len(colors_jpg))])
#blues = np.array([colors_jpg[i][:, 2] for i in range(len(colors_jpg))])
im = plt.subplots(1, 3, figsize=(15, 5))
def image_plot(idx: int, cmap: str):
    plt.subplot(1, 3, idx)
    plt.title(cmap)
    plt.imshow(colors_jpg, cmap=cmap)
    plt.axis("off")

image_plot(1, "Reds_r")
image_plot(2, "Greens_r")
image_plot(3, "Blues_r")
plt.show()



2. fill original image's second channel with zeros

3. fill original image's third channel with zeros

Explain the results

In [ ]:
from copy import deepcopy
# load image
orig = np.array(colors_jpg_nparr)
img = np.array(orig) # should perform deep copy

# fill 1st chanel with 0
#img[:,:,0] = 0  # remove all red

#plt.imshow(img)

colors_jpg_nparr.shape

(1600, 2560)

In [ ]:
im = plt.subplots(1, 3, figsize=(15, 5))
colors_jpg = Image.open("images/colors.jpg")#.convert('L')
def image_plot(idx: int, cmap: str):
    plt.subplot(1, 3, idx)
    plt.title(cmap)
    plt.imshow(colors_jpg, cmap=cmap)
    plt.axis("off")

image_plot(1, "Reds_r")
image_plot(2, "Greens_r")
image_plot(3, "Blues_r")
plt.show()


(d) To transform an RGB image to grayscale, you need to take a weighted average of the different color channels :

$$grayscale = 0.2989 \times R + 0.5870 \times G + 0.1140 \times B$$

where, R,G,B are the red blue and green channels extracted (sliced) from the image.

1. Implement this operation using *Numpy* @ operator between the original image and the weight vector

$$w = [0.2125, 0.7154, 0.0721]$$

2. Obtain the same result by using the function *skimage.color.rgb2gray()*. Display it.

3. Compute singlechannel image by performing simple averaging of the color channels. Display it.

3. Compare the images, that you have obtained. Explain the differences and similarities in results.

(e) On a 1x3 subplot, display the three histograms of the three color components separately (you may want to use the function plt.hist())

### Exercise 2 : Numpy matrices

*(1 point)*

(a) Using *Numpy*, generate a gradient image like the one represented below :

<img src="https://github.com/David-Kyrat/13X004-image-processing/blob/master/tp01/images/grad.png?raw=1" alt="drawing" width="400"/>

* Its shape should be $[125, 500]$
* Its dynamic range should be 0 to 255 encoded in a UINT8 array

and display it using *matplotlib*.

(b) Generate the images that are represented below using Numpy arrays of shape [2,2] and dtype boolean. Visualize the results on a $1 \times 3$ grid.

<img src="https://github.com/David-Kyrat/13X004-image-processing/blob/master/tp01/images/black_and_white.png?raw=1" alt="drawing" width="800"/>

(c) Find a way to write the third array as a combination of the first two using *numpy* operators (addition, multiplication, *np.bitwise_and()*, *np.bitwise_not(), ...*)

(d) By correctly using color channels, only manipulating the gradient image you produced in (a), and the functions

* *np.stack()*
* *np.zeros_like()*

Produce the following image :

<img src="https://github.com/David-Kyrat/13X004-image-processing/blob/master/tp01/images/color_grad.png?raw=1" alt="drawing" width="400"/>

---

### Exercise 3 : Numpy operators
*(1 point)*

(a) Read the image *lena.png* and display it. What is its dtype ? its dynamic range ? How many color channels does it have ?

(b) Compute the MSE (L2 distance) between the two grayscale images (any two grayscale images from Ex. 1.d) by using *np.linalg.norm()*. Comment on the value.

(c) On the grayscale image, crop the face of Lena using a rectangle with coordinates :

* Top-left (150, 100)
* Down-right (375, 380)

By using *Numpy* array slicing

(d) Normalize the RGB _lena.png_ image. First convert image to _np.float32_ and scale to _[0, 1]_ dynamic range, then substract _0.5_ from each color channel and divide each channel by _0.5_. Use Numpy scalar on matrix operations.

### Exercise 4 : Gaussian noise
*(1 point)*

Read the image *lena.png* and convert it to grayscale. Ensure that it has dtype _np.float32_ with dynamic range _[0, 1]_.

(a) Define a *Numpy* array of same shape as the image, with each entry randomly sampled from a Gaussian distribution $\mathcal{N}(0, \sigma^2)$ with $\sigma = 0.01, 0.3, 0.5$.

Hint : Use *np.random.randn()* function

(b) Add this noise to the grayscale image using numpy array addition and visualise the results on a 1x3 subplot.

(c) Redo the preceding step using the function *skimage.util.random_noise()* with parameter *clip=True*.

(d) Explain why, for the same $\sigma$, the two methods yield different visual results.

--- Write your answer here ---

---

### Exercise 5 : Salt & Pepper Noise

*(1 point)*

Read the image *lena.png* and convert it to grayscale. Make sure that it has dtype float with dynamic range [0,1].

(a) Using *skimage.util.random_noise()* add the Salt & Pepper noise with density

$$\rho = 0.01, 0.1, 0.5$$

and display the results.

(b) Explain the differences between the Gaussian noise and the S&P noise. Which one do you think is harder to remove ? Why ?

--- Write your answer here ---

(c) Write your own function that adds salt and pepper noise to the image. As inputs the function should take: input image - np.ndarray, p - percentage of the pixels to be replaced with noise. Make sure that your function works with singlechannel and multichannel images

In [ ]:
import numpy as np
def add_salt_and_pepper(im_input: np.ndarray, p: float) -> np.ndarray:
    pass

---

### Exercise 6 : Mean and variance

*(1 point)*

Read the image *lena.png* and convert it to grayscale. Make sure that it has dtype _np.float32_ with dynamic range _[0, 1]_.

(a) Compute the global mean and the global variance of the image using *np.mean()* and *np.std()*

Read the image *lena.png* as RGB image. Make sure that it has dtype _np.float32_ with dynamic range _[0, 1]_.

(b) Compute the global mean and the global variance of each image channel using *np.mean()* and *np.std()*.

_Hint_: use _axis_ parameter in _np.mean()_ and _np.std()_ functions

(c) Compute the local mean and variance of the image for a window size $5 \times 5$ with splitting
steps 1 and 3. Display the obtained results as new (smaller) images. Explain the change
in the image size and give an interpretation of the results, from an image processing point
of view.

*Hint :* You may use the function *view_as_windows()* from *skimage.util.shape* package.

*Note :* do not use cycle, use Numpy array operations

---